#!/bin/sh
set -e

# ---------------------------------------------------------------------------
# SplitIt reverse-proxy entrypoint
# Renders nginx.conf from template and ensures TLS material is available.
# Runs as the nginx non-root user; never executes destructive cert operations.
# ---------------------------------------------------------------------------

# Defaults (overridden via environment variables).
export DOMAIN="${DOMAIN:-localhost}"
export TLS_MODE="${TLS_MODE:-selfsigned}"   # 'letsencrypt' or 'selfsigned'
export BACKEND_HOST="${BACKEND_HOST:-backend}"
export FRONTEND_HOST="${FRONTEND_HOST:-frontend}"
export HTTP_LISTEN_PORT="${HTTP_LISTEN_PORT:-8080}"
export HTTPS_LISTEN_PORT="${HTTPS_LISTEN_PORT:-8443}"

CERT_DIR="/etc/nginx/ssl"
LE_DIR="/etc/letsencrypt/live/${DOMAIN}"
DH_FILE="${CERT_DIR}/dhparam.pem"

mkdir -p "${CERT_DIR}" /var/www/certbot /etc/nginx/sites-enabled

if [ "${TLS_MODE}" = "letsencrypt" ]; then
    # Production: DH parameters must be pre-generated by the operator (2048-bit minimum).
    if [ ! -f "${DH_FILE}" ]; then
        echo "ERROR: DH parameters file not found at ${DH_FILE}."
        echo "Generate with: openssl dhparam -out dhparam.pem 2048"
        echo "Then place it in the nginx_certs volume. See docs/HTTPS.md."
        exit 1
    fi
    export SSL_CERTIFICATE="${LE_DIR}/fullchain.pem"
    export SSL_CERTIFICATE_KEY="${LE_DIR}/privkey.pem"

    if [ ! -f "${SSL_CERTIFICATE}" ] || [ ! -f "${SSL_CERTIFICATE_KEY}" ]; then
        echo "ERROR: Let's Encrypt certificate for ${DOMAIN} not found at ${LE_DIR}."
        echo "Run the certbot issue/renew workflow before starting the proxy."
        echo "See docs/HTTPS.md for instructions."
        exit 1
    fi
else
    # Self-signed mode: used for local HTTPS testing only.
    export SSL_CERTIFICATE="${CERT_DIR}/nginx.crt"
    export SSL_CERTIFICATE_KEY="${CERT_DIR}/nginx.key"

    if [ ! -f "${DH_FILE}" ]; then
        echo "Generating DH parameters (2048-bit) — this happens once..."
        openssl dhparam -out "${DH_FILE}" 2048
    fi

    if [ ! -f "${SSL_CERTIFICATE}" ] || [ ! -f "${SSL_CERTIFICATE_KEY}" ]; then
        echo "Generating self-signed certificate for ${DOMAIN}..."
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
            -keyout "${SSL_CERTIFICATE_KEY}" \
            -out "${SSL_CERTIFICATE}" \
            -subj "/CN=${DOMAIN}" \
            -addext "subjectAltName=DNS:${DOMAIN},DNS:localhost,IP:127.0.0.1"
        chmod 600 "${SSL_CERTIFICATE_KEY}"
        chmod 644 "${SSL_CERTIFICATE}"
        echo "Self-signed certificate created. NOT for production use."
    fi
fi

# Render the final nginx configuration from the template.
envsubst '$DOMAIN $TLS_MODE $BACKEND_HOST $FRONTEND_HOST $HTTP_LISTEN_PORT $HTTPS_LISTEN_PORT $SSL_CERTIFICATE $SSL_CERTIFICATE_KEY' \
    < /etc/nginx/nginx.conf.template \
    > /etc/nginx/nginx.conf

# Validate configuration before starting.
nginx -t

# --- Phase 12: background watcher for Let's Encrypt renewal reload ---
# The certbot-renewer service writes a sentinel file to the shared certbot_www
# volume after a successful certificate renewal (via certbot --deploy-hook).
# This watcher checks for the sentinel every 60s and reloads Nginx so the new
# certificate is picked up without restarting the proxy container.
RELOAD_SENTINEL="/var/www/certbot/.reload-trigger"
(
    while true; do
        if [ -f "${RELOAD_SENTINEL}" ]; then
            rm -f "${RELOAD_SENTINEL}" 2>/dev/null || true
            echo "[$(date)] Certificate renewal detected. Reloading Nginx..."
            nginx -s reload 2>/dev/null || true
        fi
        sleep 60
    done
) &

echo "Starting SplitIt reverse proxy — domain=${DOMAIN}, tls=${TLS_MODE}, http=${HTTP_LISTEN_PORT}, https=${HTTPS_LISTEN_PORT}"

exec "$@"
